options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _PROJECT_ID: midyear-precept-472409-k3
  _GKE_CLUSTER: savoryroute-microservice
  _GKE_REGION: asia-south1

steps:
  # 1️⃣ Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'asia-south1-docker.pkg.dev/$_PROJECT_ID/my-repo/gateway-service:$COMMIT_SHA',
        '-f', 'api-gateway/Dockerfile',
        'api-gateway'
      ]

  # 2️⃣ Push image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-south1-docker.pkg.dev/$_PROJECT_ID/my-repo/gateway-service:$COMMIT_SHA'
      ]

  # 3️⃣ Configure GKE credentials
  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials $_GKE_CLUSTER \
          --region $_GKE_REGION \
          --project $_PROJECT_ID
        kubectl apply -f api-gateway/k8s/gateway-service.yaml


images:
  - 'asia-south1-docker.pkg.dev/$_PROJECT_ID/my-repo/gateway-service:$COMMIT_SHA'
