spring.application.name=eureka-server
server.port=8761

# Eureka server standalone
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Prefer IP address
eureka.instance.prefer-ip-address=true
# Eureka clients will access through LoadBalancer IP
eureka.instance.hostname=34.93.159.51