options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _IMAGE_NAME: server-service
  _GKE_CLUSTER: savoryroute-microservice
  _GKE_REGION: asia-south1
  _PROJECT_ID: midyear-precept-472409-k3

steps:
  # 1️⃣ Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'asia-south1-docker.pkg.dev/$_PROJECT_ID/my-repo/$_IMAGE_NAME:$COMMIT_SHA',
        '-f', 'server/Dockerfile',
        'server'
      ]

  # 2️⃣ Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-south1-docker.pkg.dev/$_PROJECT_ID/my-repo/$_IMAGE_NAME:$COMMIT_SHA'
      ]

  # 3️⃣ Configure GKE credentials and deploy in one step
  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials $_GKE_CLUSTER \
          --region $_GKE_REGION \
          --project $_PROJECT_ID
        kubectl apply -f server/k8s/$_IMAGE_NAME.yaml

images:
  - 'asia-south1-docker.pkg.dev/$_PROJECT_ID/my-repo/$_IMAGE_NAME:$COMMIT_SHA'
